### ISSUE TITLE
Way to modify code to obtain all solutions to the digits puzzle and not just one?

### ISSUE THREAD

**Issue by yangchris16** [outofmbufs/NYTDigits#1]
Hi, I'm trying to find a way to generate a list of all possible permutations of solutions for the digits game.  I appreciate your code but can't follow it well enough to figure out how to modify it to list all possible solutions to the puzzle.  If it's easy to modify, please let me know.  thanks

**Comment by outofmbufs** [comment]
(sorry didn't notice this until now) ... take a look at this, now try solve(puzzle, n=10000) for example to return 10000 solutions (in an array of individual solutions). It will stop if it reaches the end, so this is a way to get them "all" just make n= big enough.

**Comment by outofmbufs** [comment]
... and just added support for this to the command-line. See the new README file. Thanks!
